baseURL = 'https://antost.dev/'
languageCode = 'en-us'
title = 'Antoni Ostrowski'
disableKinds = ['taxonomy', 'term']

[params]
  description = 'Personal site and projects of Antoni Ostrowski.'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
